### ISSUE TITLE
tiff isn't recognized

### ISSUE THREAD

**Issue by hgoetzger** [arimus/jmimemagic#18]
running with tiff file from https://github.com/arimus/jmimemagic/tree/master/test_docs :

```
import java.io.File;
import net.sf.jmimemagic.Magic;
import net.sf.jmimemagic.MagicMatch;
public class TiffCheck {
   public static void main(String[] args) {
      // image/tiff
      // TIFF image data, little-endian
      checkJmimemagic("test_nocompress.tif");
   }
   // net.sf.jmimemagic
   public static void checkJmimemagic(final String file) {
      String mimeType = null;
      try {
         File currentFile = new File(file);
         MagicMatch match = Magic.getMagicMatch(currentFile, true, false);
         mimeType = match.getMimeType();
         System.out.println(mimeType);
      } catch (Exception e) {
         e.printStackTrace();
      }
   }
}
```

delivers:

```
net.sf.jmimemagic.MagicMatchNotFoundException
    at net.sf.jmimemagic.Magic.getMagicMatch(Magic.java:368)
    at TiffCheck.checkJmimemagic(TiffCheck.java:22)
    at TiffCheck.main(TiffCheck.java:13)
```

Can you please confirm or tell me what's wrong with my test.

Thanks
Cheers

Heinrich

**Comment by lokireddy** [comment]
how to solve this problem.

**Comment by arimus** [comment]
@lokireddy I'm not sure what you mean? I pushed support for TIFF into the magic.xml definitions, so you should be able to use those in your magic.xml file or rebuild the latest.
